### PR TITLE
Adding spaces and spaces_info modules

### LINKED ISSUE #215: [Feature] DigitalOcean Spaces
##### SUMMARY
Supporting DigitalOcean Spaces. Creation, information, etc

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
N/A, as it doesn't exist

##### ADDITIONAL INFORMATION
Pretty self-explanatory. Just getting support for Spaces creation and the like

N/A

### PR DESCRIPTION
**Pull request by mamercad**
##### SUMMARY

Fixes #215.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

* digital_ocean_spaces_info
* digital_ocean_spaces

##### ADDITIONAL INFORMATION

```paste below
TASK [List Spaces in nyc3] ***************************************************************************
ok: [localhost] => changed=false 
  data:
    spaces:
    - endpoint_url: https://nyc3.digitaloceanspaces.com
      name: gh-ci-space
      region: nyc3
      space_url: https://gh-ci-space.nyc3.digitaloceanspaces.com

TASK [List Spaces in sfo3] ***************************************************************************
ok: [localhost] => changed=false 
  data:
    spaces: []

TASK [Create a Space in nyc3] ************************************************************************
changed: [localhost] => changed=true 
  data:
    space:
      endpoint_url: https://nyc3.digitaloceanspaces.com
      name: gh-ci-space-1
      region: nyc3
      space_url: https://gh-ci-space-1.nyc3.digitaloceanspaces.com
  msg: Created Space gh-ci-space-1 in nyc3

TASK [List Spaces in nyc3] ***************************************************************************
ok: [localhost] => changed=false 
  data:
    spaces:
    - endpoint_url: https://nyc3.digitaloceanspaces.com
      name: gh-ci-space
      region: nyc3
      space_url: https://gh-ci-space.nyc3.digitaloceanspaces.com
    - endpoint_url: https://nyc3.digitaloceanspaces.com
      name: gh-ci-space-1
      region: nyc3
      space_url: https://gh-ci-space-1.nyc3.digitaloceanspaces.com

TASK [Pause for a minute] ****************************************************************************
Pausing for 60 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost] => changed=false 
  delta: 60
  echo: true
  rc: 0
  start: '2022-01-15 20:08:18.142790'
  stderr: ''
  stdout: Paused for 1.0 minutes
  stop: '2022-01-15 20:09:18.146106'
  user_input: ''

TASK [Delete a Space in nyc3] ************************************************************************
changed: [localhost] => changed=true 
  msg: Deleted Space gh-ci-space-1 in nyc3

TASK [List Spaces in nyc3] ***************************************************************************
ok: [localhost] => changed=false 
  data:
    spaces:
    - endpoint_url: https://nyc3.digitaloceanspaces.com
      name: gh-ci-space
      region: nyc3
      space_url: https://gh-ci-space.nyc3.digitaloceanspaces.com

PLAY RECAP *******************************************************************************************
localhost                  : ok=7    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### CODE REVIEW

**Comment by mamercad** [comment]
This isn't ready, I need to write the integration tests, create a changelog fragment, etc.

**Comment by mamercad** [comment]
Here are the tasks if you're interested:

```
    - name: List Spaces in nyc3
      community.digitalocean.digital_ocean_spaces_info:
        state: present
        name: my-space
        region: nyc3

    - name: List Spaces in sfo3
      community.digitalocean.digital_ocean_spaces_info:
        state: present
        name: my-space
        region: sfo3

    - name: Create a Space in nyc3
      community.digitalocean.digital_ocean_spaces:
        state: present
        name: gh-ci-space-1
        region: nyc3

    - name: List Spaces in nyc3
      community.digitalocean.digital_ocean_spaces_info:
        state: present
        name: my-space
        region: nyc3

    - name: Pause for a minute
      ansible.builtin.pause:
        minutes: 1

    - name: Delete a Space in nyc3
      community.digitalocean.digital_ocean_spaces:
        state: absent
        name: gh-ci-space-1
        region: nyc3

    - name: List Spaces in nyc3
      community.digitalocean.digital_ocean_spaces_info:
        state: present
        name: my-space
        region: nyc3
```

**Comment by mamercad** [comment]
I'm using the standard AWS environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

**Comment by mamercad** [comment]
I think that since I'm changing workflow things, I need this to land in `main` before the tests will work. Here's the result in the `ci` branch: https://github.com/ansible-collections/community.digitalocean/runs/4842338929?check_suite_focus=true (passing).

**Review by mpontillo — APPROVED** [review]

**Pull request merged**
