### PR TITLE
issues/223 fix digitalocean api documentation links

### LINKED ISSUE #223: DigitalOcean API Doc Links Are Outdated; Redirects to New Docs Do Not Respect Anchors
##### SUMMARY
All references to the DigitalOcean API docs have links to an old URL for the docs (developers.digitalocean.com/documention).
These will links redirect to the new docs (docs.digitalocean.com/reference/api/api-reference), but the anchors are different on the new page, so they are not respected.

ex:
Documentation has the link https://developers.digitalocean.com/documentation/v2/#list-all-keys
which redirects just to https://docs.digitalocean.com/reference/api/api-reference/
when the correct link is
https://docs.digitalocean.com/reference/api/api-reference/#operation/list_all_keys

##### ISSUE TYPE
- Documentation Report

### PR DESCRIPTION
**Pull request by francoposa**
##### SUMMARY
Fixes #223 

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by mamercad** [comment]
Thanks for fixing this, you'll need to add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) as well please!

**Review by mamercad — CHANGES_REQUESTED** [review]
Thanks, just waiting on the changelog fragment.

**Comment by francoposa** [comment]
I added changelog referencing the issue #, let me know if you prefer it to reference the PR #

**Review by mamercad — APPROVED** [review]
Thanks again for updating these!

**Pull request merged**
