### PR TITLE
Add an action_group to default vars for every module

### PR DESCRIPTION
**Pull request by dmsimard**
##### SUMMARY

Add an action_group to default vars for every module

This allows, for example, to default the value of oauth_token once
without needing to specify it in every task unless it needs to be
overridden.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

meta/runtime.yml

##### ADDITIONAL INFORMATION

Inspired by azure.azcollection's recent fix: https://github.com/ansible-collections/azure/pull/874

Edit: it looks like this for the example in the README:

Screenshot from 2022-08-17 23-26-56

### CODE REVIEW

**Comment by dmsimard** [comment]
The failure doesn't appear to be related to the patch at first glance:
Screenshot from 2022-08-17 23-16-16

I've clicked the button to re-run the integration test job because it's been a while and would be interested in a recent result.

**Comment by mamercad** [comment]
I think all this needs at this point is a changelog fragment ...

**Review by mamercad — CHANGES_REQUESTED** [review]
Changelog fragment please!

**Comment by dmsimard** [comment]
I'll provide a fragment, are you otherwise OK with the name ?

I also wonder what's the best way to keep an updated list of modules here and they are added and removed from the collection.

I came up with this list with a bit of bash-fu but I wonder if there is a better way :p

**Comment by dmsimard** [comment]
> Changelog fragment please!

Done !

**Comment by mamercad** [comment]
> I'll provide a fragment, are you otherwise OK with the name ?
> 
> I also wonder what's the best way to keep an updated list of modules here as they are added and removed from the collection.
> 
> I came up with this list with a bit of bash-fu but I wonder if there is a better way :p

Hehe, I have nothing beyond this:

```bash
❯ grep 'module:' plugins/modules/*.py | awk '{print $2}' | sort | uniq
digital_ocean
digital_ocean_account_info
digital_ocean_balance_info
digital_ocean_block_storage
digital_ocean_cdn_endpoints
digital_ocean_cdn_endpoints_info
digital_ocean_certificate
digital_ocean_certificate_info
digital_ocean_database
digital_ocean_database_info
digital_ocean_domain
digital_ocean_domain_info
digital_ocean_domain_record
digital_ocean_domain_record_info
digital_ocean_droplet
digital_ocean_droplet_info
digital_ocean_firewall
digital_ocean_firewall_info
digital_ocean_floating_ip
digital_ocean_floating_ip_info
digital_ocean_image_info
digital_ocean_kubernetes
digital_ocean_kubernetes_info
digital_ocean_load_balancer
digital_ocean_load_balancer_info
digital_ocean_monitoring_alerts
digital_ocean_monitoring_alerts_info
digital_ocean_project
digital_ocean_project_info
digital_ocean_region_info
digital_ocean_size_info
digital_ocean_snapshot
digital_ocean_snapshot_info
digital_ocean_spaces
digital_ocean_spaces_info
digital_ocean_sshkey
digital_ocean_sshkey_info
digital_ocean_tag
digital_ocean_tag_info
digital_ocean_volume_info
digital_ocean_vpc
digital_ocean_vpc_info
```

**Comment by mamercad** [comment]
This is a slick feature by the way, thanks for sharing!

**Review by mamercad — APPROVED** [review]
🚢

**Pull request merged**
