### PR TITLE
Integration Tests

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY
Following on from the great work done in https://github.com/ansible-collections/community.digitalocean/pull/59

GitHub secrets aren't available in forks, so use a branch within the repo.
##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by mamercad** [comment]
Fixes #62.

**Comment by mamercad** [comment]
Full run [here](https://github.com/ansible-collections/community.digitalocean/actions/runs/760746074).

**Comment by mamercad** [comment]
I cancelled a bunch of them above to save time/money.

**Comment by mamercad** [comment]
Adding `cloud/digitalocean` to `ansible-test` is happening [here](https://github.com/ansible/ansible/pull/74222).

**Comment by gundalow** [comment]
Coverage is working now https://codecov.io/gh/ansible-collections/community.digitalocean/tree/e1954cfaa2ad7854e26526c19800201b2a391864/plugins

**Comment by mamercad** [comment]
> Coverage is working now https://codecov.io/gh/ansible-collections/community.digitalocean/tree/e1954cfaa2ad7854e26526c19800201b2a391864/plugins

Hrm, can you see the results of [this](https://codecov.io/gh/ansible-collections/community.digitalocean/src/e1954cfaa2ad7854e26526c19800201b2a391864/plugins/modules/digital_ocean_balance_info.py)? I'm getting "GitHub API: Forbidden".

**Review by mamercad — APPROVED** [review]
I'm happy with things at this point, 🚢 .

**Review by mamercad — APPROVED** [review]
🚢

**Pull request merged**
