### PR TITLE
Support templating of the API token

### PR DESCRIPTION
**Pull request by maxtruxa**
##### SUMMARY
This PR adds support for templates in the API token field. This mechanism allows retrieving the password from arbitrary sources (for example, a password manager).

##### TODO
- [x] Add documentation.
- [x] Add tests.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Inventory plugin

##### ADDITIONAL INFORMATION
Example script `get-do-token.sh` that just writes the API token to stdout:
```sh
#!/usr/bin/env sh

# You can do whatever you want here.
echo 'your-api-token-here'
```
Inventory config `inventory_digitalocean.yml`, referencing the script:
```yml
plugin: community.digitalocean.digitalocean
api_token: '{{ lookup("pipe", "./get-do-token.sh") }}'
```

### CODE REVIEW

**Comment by mamercad** [comment]
This is a neat idea, thank's for contributing.

**Comment by mamercad** [comment]
I wonder if there's a function we can call to trigger interpolation, like this:

```yaml
plugin: community.digitalocean.digitalocean
api_token: "{{ lookup('pipe', './get-do-token.sh') }}"
```

**Comment by maxtruxa** [comment]
Oh that is actually a much better idea. That shouldn't be too hard to implement, since it's being used all over the place in Ansible. I'll look into it later today.

**Comment by maxtruxa** [comment]
@mamercad Done!

I changed the example to showcase the use of a `lookup`, because the old example was broken.

**Review by mamercad — APPROVED** [review]
This is great -- thanks so very much! 🎉

**Pull request merged**
