### PR TITLE
Use get_paginated_data when retrieving list of domains

### LINKED ISSUE #306: digital_ocean_domain: Fails if you have more than 20 domains
##### SUMMARY
The `digital_ocean_domain` module fails if you have more than 20 domains in your project. This is because the Digitial Ocean domains api list endpoint is paginated with a default value of 20 (docs: https://docs.digitalocean.com/reference/api/api-reference/#operation/domains_list)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
* digital_ocean_domain module

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.5]
  config file = None
  configured module search path = ['/home/tank/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tank/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/tank/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/tank/.local/bin/ansible
  python version = 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/tank/.local/lib/python3.10/site-packages/ansible_collections
Collection             Version
---------------------- -------
community.digitalocean 1.23.0 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

* MacBook Pro Apple M1 Ventura 13.3.1
* Python 3.10

##### STEPS TO REPRODUCE

* Have more than 20 domains in your Digital Ocean account/project
* Run the playbook below with a domain that is greater than 20 on your list of domains and already exists

```yaml
- hosts: localhost
  tasks:
    - name: Create a domain
      community.digitalocean.digital_ocean_domain:
        state: present
        name: my.digitalocean.domain
```

##### EXPECTED RESULTS

* The module should cope with the fact that the domain already exists and report no changes necessary

##### ACTUAL RESULTS

* Due to the pagination issue the domain is not found by the digital_ocean_domain module and the module tries to create the already existing domain
* The Digital Ocean api errors (because the domain already exists) causing the playbook to fail

```paste below
Data domain 'my.digitalodean.domain': name already exists
```

### PR DESCRIPTION
**Pull request by elcfd**
##### SUMMARY

Fixes #306 by using get_paginated_data

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

digital_ocean_domain module

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by mamercad** [comment]
> Hi @mamercad apologies for bothering you like this but is there an ETA on when this can be looked at? Currently having to run this module with a patch in my infrastructure. Thanks @elcfd

Apologies, I've been swamped at `$work`, looking now.

**Review by mamercad — CHANGES_REQUESTED** [review]
Thanks for this, please kindly add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments).

**Comment by elcfd** [comment]
Hi @mamercad no problem - have added the changelog fragement as requested.

**Comment by mamercad** [comment]
I think we'll need #310 before this passes tests, I'm working on it.

**Comment by mamercad** [comment]
> I think we'll need #310 before this passes tests, I'm working on it.

@elcfd kindly rebase this against `main` and let's see how the tests look.

**Comment by elcfd** [comment]
@mamercad have rebased against ```main``` as requested

**Comment by mamercad** [comment]
Thanks for this ❤️

**Comment by elcfd** [comment]
> Thanks for this heart

@mamercad not a problem - glad to have sorted the bug - thanks for the help merging

**Pull request merged**
