### PR TITLE
Fix Droplet integration tests

### PR DESCRIPTION
**Pull request by mamercad**
##### SUMMARY

Fix Droplet integration tests

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

* `digital_ocean_droplet`

### CODE REVIEW

**Review by mpontillo — APPROVED** [review]
Looks good. My only suggestion: use `time.monotonic()` rather than `time.time()` where possible.

**Comment by mamercad** [comment]
I pushed my changes to the `ci` branch, [here's the run, it passed](https://github.com/ansible-collections/community.digitalocean/actions/runs/858539151).

**Comment by mamercad** [comment]
recheck

**Review by mpontillo — APPROVED** [review]
lgtm!

**Pull request merged**
