### PR TITLE
Add project resource info module

### LINKED ISSUE #323: Module to retrieve project resources
##### SUMMARY
Module to retrieve project resources will be very useful, for example in integration tests and also it will lead to more coverage of the existing do rest api. You can see the exact api [here](https://docs.digitalocean.com/reference/api/api-reference/#tag/Project-Resources).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Need a new module, something like digital_ocean_project_resource_info.

##### ADDITIONAL INFORMATION

Currently, it is not so easy to test with integration test features that add the possibility to assign some resources to some projects. For example [this one](https://github.com/ansible-collections/community.digitalocean/issues/264). If there is a module to retrieve project resources, then it will be straightforward.

### PR DESCRIPTION
**Pull request by raman-babich**
##### SUMMARY

Fixes #323 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

project resource info module

### CODE REVIEW

**Comment by raman-babich** [comment]
@mamercad as I can see you had some commits to the repository some time ago, is there any way to merge my contributions? BTW I also want to provide prs for some other issues of this repo.

**Comment by mamercad** [comment]
> @mamercad as I can see you had some commits to the repository some time ago, is there any way to merge my contributions? BTW I also want to provide prs for some other issues of this repo.



> @mamercad as I can see you had some commits to the repository some time ago, is there any way to merge my contributions? BTW I also want to provide prs for some other issues of this repo.

Sure, mind getting the tests passing?

**Comment by raman-babich** [comment]
I think the tests should be green now.

**Comment by raman-babich** [comment]
Sorry, pylint on my local machine could not find these issues. I force-pushed a fix.

**Comment by mamercad** [comment]
Thanks for working on this, mind adding a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments)?

**Comment by raman-babich** [comment]
Don't know if it is everything that I should mention in it, but I have added it.

**Review by mamercad — APPROVED** [review]
🚢

**Pull request merged**
