### PR TITLE
Fix #21, make digital_ocean_domain idempotent

### LINKED ISSUE #21: digital_ocean_domain is not idempotent
##### SUMMARY
digital_ocean_domain is not idempotent. I created the domain fine, but on a 2nd run, it fail with a error message, and from a quick code reading, seems to be caused by the fact I added a domain without adding a IP or anything. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
digital_ocean_domain 

##### ANSIBLE VERSION

```paste below
 $ ansible --version
ansible 2.9.9
  config file = /home/misc/.ansible.cfg
  configured module search path = [u'/home/misc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- name: Add the domain in DO
  digital_ocean_domain:
    state: present
    name: do.example.org
    oauth_token: "{{ digital_ocean_token }}"

```

##### EXPECTED RESULTS
Not fail

##### ACTUAL RESULTS
Fail with a traceback:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_digital_ocean_domain_payload_998_9rik/ansible_digital_ocean_domain_payload.zip/ansible/modules/cloud/digital_ocean/digital_ocean_domain.py", line 214, in main
  File "/tmp/ansible_digital_ocean_domain_payload_998_9rik/ansible_digital_ocean_domain_payload.zip/ansible/modules/cloud/digital_ocean/digital_ocean_domain.py", line 176, in core
  File "/tmp/ansible_digital_ocean_domain_payload_998_9rik/ansible_digital_ocean_domain_payload.zip/ansible/modules/cloud/digital_ocean/digital_ocean_domain.py", line 153, in create_domain_record
KeyError: 'domain_record'
fatal: [bastion.example.org]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "id": null,
            "ip": null,
            "name": "do.example.org",
            "oauth_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "timeout": 30,
            "validate_certs": true
        }
    },
    "msg": "'domain_record'"
}

```

### PR DESCRIPTION
**Pull request by mscherer**
If the user do not give a IP for the @ record, we shouldn't
try to add 1.

##### SUMMARY

Fix #21 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
digital_ocean_domain

### CODE REVIEW

**Review by mamercad — APPROVED** [review]
LGTM (tested locally as well)

**Comment by jdoss** [comment]
Hey folks, can we get this fix merged?

**Comment by mamercad** [comment]
Sorry for taking so long on this. Unfortunately, it seems like "something else is actually broken".

Take a look at this output: https://gist.github.com/mamercad/8effa85bd0381ab164682b78ca5b6a88

Here's the playbook: https://gist.github.com/mamercad/afe7db39085aa88b4833224a486f4b4b

It seems like there's a different problem: the first run shows "changed" (which is correct since they domain didn't exist), but, it doesn't give back the zone information (this seems like the *actual* bug). The subsequent run, without changing the play, show as "ok" and return the zone information (which is correct since nothing is changing).

Let's look into this a bit closer.

**Comment by mpontillo** [comment]
Mark and I reviewed this further and we agreed that it's a good improvement; thanks for your contribution!

**Comment by jdoss** [comment]
Thanks all!

**Comment by mamercad** [comment]
> Thanks all!

No, thank you :)

**Pull request merged**
